languageCode = "de"
languageName = "Deutsch"
weight = 1
title = ""

[params]
  description = ""
  displayName = "DE"
  isoCode = "de"
  rtl = false
  dateFormat = "2 January 2006"

[author]
  name = "Like peppermind and honey"
  image = "img/logo.png"
  links = [
  { instagram = "https://www.instagram.com/like_peppermind_and_honey/" },
  { email = "mailto:info@peppermind-and-honey.de"}
]
#headline = "welcome"
#bio = "???"